sections:
  main:
    display: Main
    fields:
      title:
        display: Title
        type: text
        width: 50
        localizable: true
      slug:
        display: Slug
        type: text
        width: 50
      releases:
        max_items: 1
        type: collections
        width: 50
        display: Releases
      bug_fixes:
        max_items: 1
        type: collections
        width: 50
        display: 'Bug Fixes'
      main_content:
        buttons:
          - h2
          - h3
          - bold
          - italic
          - unorderedlist
          - orderedlist
          - removeformat
          - quote
          - anchor
        style: sans
        spellcheck: true
        allow_source: true
        allow_internal_links: true
        link_noopener: false
        link_noreferrer: false
        target_blank: false
        semantic_elements: false
        restrict_assets: false
        sets:
          image:
            display: Image
            fields:
              image:
                container: main
                folder: /
                restrict: false
                max_files: 1
                type: assets
                display: Image
          latest_release:
            display: 'Latest Release'
            fields:
              release:
                max_items: '1'
                collection: {  }
                type: collection
                display: Release
        type: bard
        display: 'Main Content'
taxonomies: false
title: Product
